//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moe_aems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolCluster
    {
        public SchoolCluster()
        {
            this.Schools = new HashSet<School>();
        }
    
        public string Code { get; set; }
        public string Description { get; set; }
        public string Zone { get; set; }
        public int SortNo { get; set; }
    
        private ICollection<School> Schools { get; set; }
        public virtual SchoolZone SchoolZone { get; set; }
    }
}
