//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moe_aems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolZone
    {
        public SchoolZone()
        {
            this.SchoolClusters = new HashSet<SchoolCluster>();
        }
    
        public string Code { get; set; }
        public string Description { get; set; }
        public int SortNo { get; set; }
        public string ShortDescription { get; set; }
    
        private ICollection<SchoolCluster> SchoolClusters { get; set; }
    }
}
