//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moe_aems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int Id { get; set; }
        public string SchoolCode { get; set; }
        public string SchoolName { get; set; }
        public string SchoolType { get; set; }
        public string SchoolLevel { get; set; }
        public string Cluster { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string PrincipalName { get; set; }
        public string VpName { get; set; }
        public string AdminVPName { get; set; }
        public int SchoolYear { get; set; }
        public string EvenOdd { get; set; }
        public bool ExtendSADeadline { get; set; }
        public Nullable<System.DateTime> NewSADeadline { get; set; }
        public int ExceptionYearForApplyAward { get; set; }
        public bool IntegratedProgramme { get; set; }
        public string Status { get; set; }
        public Nullable<int> EV20012005 { get; set; }
        public Nullable<int> EV20062010 { get; set; }
        public Nullable<int> EV20112015 { get; set; }
        public Nullable<int> EV20162020 { get; set; }
        public bool ExtendDeclareDeadline { get; set; }
        public Nullable<System.DateTime> NewDeclareDeadline { get; set; }
        public bool ExtendAwardAppDeadline { get; set; }
        public Nullable<System.DateTime> NewAwardAppDeadline { get; set; }
        public Nullable<int> NXTEVYEAR { get; set; }
        public Nullable<bool> BESTPRACTICE { get; set; }
        public Nullable<int> SASubmissionYear { get; set; }
        public Nullable<int> ActiveYear { get; set; }
        public Nullable<int> InActiveYear { get; set; }
    
        public virtual SchoolCluster SchoolCluster { get; set; }
    }
}
